const boardEl = document.getElementById("board")
const statusEL = document.getElementById("status")
const turnEl= document.getElementById("turn")
const resetBtn= document.getElementById("resetBtn")
const newGameBtn= document.getElementById("newGameBtn")
const scoreXEl= document.getElementById("scoreX")
const scoreOEl= document.getElementById("scoreO")
